# This file was generated by GoReleaser. DO NOT EDIT.
cask "vsg" do
  name "vsg"
  desc "Vault Secrets Generator - CLI tool for managing secrets in HashiCorp Vault"
  homepage "https://github.com/pavlenkoa/vault-secrets-generator"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vsg"

  on_macos do
    on_intel do
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v#{version}/vsg_#{version}_darwin_amd64.tar.gz"
      sha256 "ffac362ed8ed7c70aa11c03b4a172290176570341e2208a76fb9b5605e975752"
    end
    on_arm do
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v#{version}/vsg_#{version}_darwin_arm64.tar.gz"
      sha256 "87ecd6e050d73c2769058091235fd7da3aefb9ef6d0222b7399a99d3ab8d4ede"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v#{version}/vsg_#{version}_linux_amd64.tar.gz"
      sha256 "110b35f8eb32747d40ebbe8391097963dba3adab9651e86ba6cded7d2c63c3b6"
    end
    on_arm do
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v#{version}/vsg_#{version}_linux_arm64.tar.gz"
      sha256 "fc677d0d8d561f3b8a1def7fd01c940a9ef74dc1e29592f907891cd7c5ffe6cc"
    end
  end

  caveats do
    "To allow the binary to run on macOS, you may need to remove the quarantine attribute:"
    "  xattr -dr com.apple.quarantine $(brew --prefix)/Caskroom/vsg"
  end

  # No zap stanza required
end
