# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vsg < Formula
  desc "Vault Secrets Generator - CLI tool for managing secrets in HashiCorp Vault"
  homepage "https://github.com/pavlenkoa/vault-secrets-generator"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_darwin_amd64.tar.gz"
      sha256 "73cd09154ab0e780c082c1689ab3a651e7624b06ab6970df42d155176601a1e6"

      def install
        bin.install "vsg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_darwin_arm64.tar.gz"
      sha256 "e4fb4b5832b0fdb79861dae38229f8496c430501a586ede74fbcddc4bb2b366f"

      def install
        bin.install "vsg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_linux_amd64.tar.gz"
      sha256 "32ed3049c4fae44397c76c9eba729e05c93e4e6d415ba6ce5d44995e6ea94fbd"
      def install
        bin.install "vsg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_linux_arm64.tar.gz"
      sha256 "285f74a9743eebfda09fcf6d956d4cce9b4a0520744f950331e0091017bc3b88"
      def install
        bin.install "vsg"
      end
    end
  end

  test do
    system "#{bin}/vsg", "version"
  end
end
