# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vsg < Formula
  desc "Vault Secrets Generator - CLI tool for managing secrets in HashiCorp Vault"
  homepage "https://github.com/pavlenkoa/vault-secrets-generator"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_darwin_amd64.tar.gz"
      sha256 "f7a4ff4605ee787a76ac31801256cfccdf0d6b4471b168539b34413bb7cea42f"

      def install
        bin.install "vsg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_darwin_arm64.tar.gz"
      sha256 "491a5654f636f49e7c7a31c4bcb2c6f270fbbfa41c63973639b500c36b255d01"

      def install
        bin.install "vsg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_linux_amd64.tar.gz"
      sha256 "b2977855347912ed7f01e8443bf1c01c2dc6d40135cb590dd92a605c2434d3dc"
      def install
        bin.install "vsg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavlenkoa/vault-secrets-generator/releases/download/v2.0.0/vsg_2.0.0_linux_arm64.tar.gz"
      sha256 "98a9a1167a83474ccd3bea26e958eaa2a3129c90c0797d9f26baef7794b972c7"
      def install
        bin.install "vsg"
      end
    end
  end

  test do
    system "#{bin}/vsg", "version"
  end
end
